name: musthavesolutions.com
favicon: null
layout_spectrum: 0.5227357009425759
typography_spectrum: 0.25
title: Must Have Solutions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#252525'
    - '#545454'
    - '#ffffff'
    - '#a7a7a7'
    - '#01a8ec'
  brandStrength: 0.6361466681119055
  lightness: 0.17925983550958335
  saturation: 0.5211730189621449
  rhythmicContrast: 0.278656319482252
purpose: []
